version: '3.7'

services:
  #
  # Blockchain archive node
  #
  #substrate-node:
  #  image: docknetwork/dock-substrate
  #  hostname: substrate-node
  #  volumes:
  #    - 'substrate-data:/data'
  #  ports:
  #    - '30333:30333'
  #    - '9933:9933'
  #    - '9944:9944'
  #  command: -d /data --unsafe-ws-external --rpc-cors all --pruning=archive --name 'Polkastats v3 - Dock' --chain ./cspec/danforth_raw.json
  #  restart: on-failure
  #
  # SQL data base
  #
  postgres:
    image: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './sql/polkastats.sql:/docker-entrypoint-initdb.d/polkastats.sql'
    environment:
      POSTGRES_USER: 'polkastats'
      POSTGRES_PASSWORD: 'polkastats'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U polkastats']
      interval: 5s
      timeout: 5s
      retries: 5
  #
  # Hasura
  #
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - '8082:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://polkastats:polkastats@postgres:5432/polkastats
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  #
  # Block crawler
  #
  crawler:
    image: polkastats-backend:latest
    build:
      context: ../../
      dockerfile: ./docker/polkastats-backend/backend/Dockerfile
    depends_on:
      - 'postgres'
      # - 'substrate-node'
    restart: on-failure
    environment:
      - NODE_ENV=production
      # - WS_PROVIDER_URL=ws://substrate-node:9944
      - WS_PROVIDER_URL=wss://mainnet-node.dock.io
      - SUBSTRATE_NETWORK=substrate
      - CRAWLER_PHRAGMEN_DISABLE=1
      - CRAWLER_STAKING_DISABLE=1
      - CRAWLER_ERA_LISTENER_DISABLE=1
      - CRAWLER_ERA_HARVESTER_DISABLE=1
      # - CRAWLER_BLOCK_LISTENER_DISABLE=1
      # - CRAWLER_BLOCK_HARVESTER_DISABLE=1
#
# Persisten volumes
#
volumes:
  db-data: {}
  substrate-data: {}
